version: '3.8'
services:
    web:
        build:
            context: ./
            target: dev
        volumes:
            - .:/src
        command: npm run start:dev
        depends_on:
            - db
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: ${NODE_ENV}
            DEBUG: ${DEBUG}
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '5432:5432'
        volumes: 
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local